# Jekyll configuration

name: maex
description:

# Url is currently only used only for the RSS feed in feed.xml
url:
#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
baseurl: ''

social:
  github: mstruebing
  stackoverflow: 'mstruebing'
  xing: 'Max_Struebing2'
  twitter: 'mstruebing1'
  rss: feed.xml

# Google Analytics key, leave blank to ignore
google_analytics_key:
# Yandex metrika (https://metrica.yandex.com/) leave blanc to ignore or put true to use
yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus:
comments: false

permalink: /:year/:month/:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
#paginate: 10

highlighter: pygments

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)

exclude: ['README.md', 'LICENSE']
